import os
clear = lambda: os.system('cls')
clear()
os.system("pip install playwright_stealth")
os.system("pip install phonenumbers")
os.system("pip install easyocr")
os.system("pip install playwright_recaptcha")
os.system("pip install pycountry")
os.system('pip install selenium')
os.system('pip install colorama')
os.system('pip install pathlib')
os.system('pip install amazoncaptcha')
os.system('pip install datetime')
os.system('pip install getmac')
os.system('pip install threading')
os.system('pip install 2captcha-python')
os.system('pip install prettytable')
os.system('pip install firebase_admin')
os.system('pip install getpass')
os.system('pip install undetected-chromedriver')
os.system('pip install requests')
os.system('pip install anticaptchaofficial')
os.system('pip install phone_iso3166')
os.system('pip install phonenumbers')
os.system('pip install names')
os.system('pip install captcha_solver')
os.system('pip install bs4')
os.system('pip install prettytable')
os.system('pip install webdriver_manager')
os.system('pip install faker')
os.system('pip install pygame')
os.system('pip install pyfiglet')
os.system('pip install fake_useragent')
os.system('pip install iglob')
os.system('pip install chromedriver_autoinstaller')
os.system('py -m pip install --upgrade pip')
os.system('py -m ensurepip --upgrade')
os.system('pip install getuseragent')
os.system('pip install undetected_chromedriver')
os.system('pip install webdriver_manager')
os.system('pip install pyfiglet')
os.system('pip install colorama')
os.system('pip install names')
os.system('pip install bs4')
os.system('pip install termcolor')
os.system('pip install pycountry')
os.system('pip install phonenumbers')
os.system('pip install playwright')
os.system('playwright install')
os.system('playwright install webkit')
os.system('pip install getuseragent')
os.system('pip install fake_useragent')
os.system('pip install pyc file')
os.system('pip install msvc-runtime')
os.system('pip3 install pymongo')
os.system('pip3 install fake_headers')
os.system('pip3 install fivesim')
